# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ac6c14c094d380e1b479604be48f38e29bd6e13793578bf3025aa5d534ef111e4384e68aba4d7ea6bf742d0fb4ed50d452fe7520b46d631f99dcfd1ca138d74

test:
  secret_key_base: 2a21a8d0418e079d65ee3f83ded07af63c8e070e839eb6d803b503e7bbb376af7989377d54013bcccd048f4f1fa70f9e647b29b7b6a9966c406b2b799ce253f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
